<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillCategoriesSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            // --- আপনার আগের ৪০টি ক্যাটাগরি (অবিকল অপরিবর্তিত রাখা হয়েছে) ---
            ['name_en' => 'Cook', 'name_ar' => 'طباخ', 'name_bn' => 'রাঁধুনি', 'icon' => 'heroicon-o-fire', 'sort_order' => 1],
            ['name_en' => 'Driver (Light)', 'name_ar' => 'سائق خفيف', 'name_bn' => 'ড্রাইভার (হালকা)', 'icon' => 'heroicon-o-truck', 'sort_order' => 2],
            ['name_en' => 'Driver (Heavy)', 'name_ar' => 'سائق ثقيل', 'name_bn' => 'ড্রাইভার (ভারী)', 'icon' => 'heroicon-o-truck', 'sort_order' => 3],
            ['name_en' => 'Mason', 'name_ar' => 'بناء', 'name_bn' => 'রাজমিস্ত্রি', 'icon' => 'heroicon-o-wrench', 'sort_order' => 4],
            ['name_en' => 'Electrician', 'name_ar' => 'كهربائي', 'name_bn' => 'ইলেকট্রিশিয়ান', 'icon' => 'heroicon-o-bolt', 'sort_order' => 5],
            ['name_en' => 'Plumber', 'name_ar' => 'سباك', 'name_bn' => 'প্লাম্বার', 'icon' => 'heroicon-o-wrench-screwdriver', 'sort_order' => 6],
            ['name_en' => 'Carpenter', 'name_ar' => 'نجار', 'name_bn' => 'কাঠমিস্ত্রি', 'icon' => 'heroicon-o-wrench', 'sort_order' => 7],
            ['name_en' => 'Painter', 'name_ar' => 'دهان', 'name_bn' => 'রঙ মিস্ত্রি', 'icon' => 'heroicon-o-paint-brush', 'sort_order' => 8],
            ['name_en' => 'Welder', 'name_ar' => 'لحام', 'name_bn' => 'ওয়েল্ডার', 'icon' => 'heroicon-o-fire', 'sort_order' => 9],
            ['name_en' => 'Security Guard', 'name_ar' => 'حارس أمن', 'name_bn' => 'নিরাপত্তা প্রহরী', 'icon' => 'heroicon-o-shield-check', 'sort_order' => 10],
            ['name_en' => 'Cleaner', 'name_ar' => 'عامل نظافة', 'name_bn' => 'ক্লিনার', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 11],
            ['name_en' => 'Helper', 'name_ar' => 'مساعد', 'name_bn' => 'সাধারণ শ্রমিক', 'icon' => 'heroicon-o-hand-raised', 'sort_order' => 12],
            ['name_en' => 'Gardener', 'name_ar' => 'بستاني', 'name_bn' => 'মালী', 'icon' => 'heroicon-o-sun', 'sort_order' => 13],
            ['name_en' => 'Farmer', 'name_ar' => 'مزارع', 'name_bn' => 'কৃষক', 'icon' => 'heroicon-o-sun', 'sort_order' => 14],
            ['name_en' => 'Factory Worker', 'name_ar' => 'عامل مصنع', 'name_bn' => 'কারখানা শ্রমিক', 'icon' => 'heroicon-o-cog', 'sort_order' => 15],
            ['name_en' => 'Tailor', 'name_ar' => 'خياط', 'name_bn' => 'দর্জি', 'icon' => 'heroicon-o-scissors', 'sort_order' => 16],
            ['name_en' => 'Barber', 'name_ar' => 'حلاق', 'name_bn' => 'নাপিত', 'icon' => 'heroicon-o-scissors', 'sort_order' => 17],
            ['name_en' => 'AC Technician', 'name_ar' => 'فني تكييف', 'name_bn' => 'এসি টেকনিশিয়ান', 'icon' => 'heroicon-o-wrench-screwdriver', 'sort_order' => 18],
            ['name_en' => 'Mechanic', 'name_ar' => 'ميكانيكي', 'name_bn' => 'মেকানিক', 'icon' => 'heroicon-o-cog-6-tooth', 'sort_order' => 19],
            ['name_en' => 'Tiler', 'name_ar' => 'بلاط', 'name_bn' => 'টাইলস মিস্ত্রি', 'icon' => 'heroicon-o-squares-2x2', 'sort_order' => 20],
            ['name_en' => 'Steel Fixer', 'name_ar' => 'حداد', 'name_bn' => 'স্টিল ফিক্সার', 'icon' => 'heroicon-o-wrench', 'sort_order' => 21],
            ['name_en' => 'Scaffolder', 'name_ar' => 'سقالة', 'name_bn' => 'স্কাফোল্ডার', 'icon' => 'heroicon-o-wrench', 'sort_order' => 22],
            ['name_en' => 'Forklift Operator', 'name_ar' => 'مشغل رافعة شوكية', 'name_bn' => 'ফর্কলিফট অপারেটর', 'icon' => 'heroicon-o-arrow-up', 'sort_order' => 23],
            ['name_en' => 'Crane Operator', 'name_ar' => 'مشغل رافعة', 'name_bn' => 'ক্রেন অপারেটর', 'icon' => 'heroicon-o-arrow-up', 'sort_order' => 24],
            ['name_en' => 'Loader / Unloader', 'name_ar' => 'حمال', 'name_bn' => 'লোডার / আনলোডার', 'icon' => 'heroicon-o-archive-box', 'sort_order' => 25],
            ['name_en' => 'Packer', 'name_ar' => 'عامل تعبئة', 'name_bn' => 'প্যাকার', 'icon' => 'heroicon-o-archive-box-arrow-down', 'sort_order' => 26],
            ['name_en' => 'Salesman', 'name_ar' => 'بائع', 'name_bn' => 'সেলসম্যান', 'icon' => 'heroicon-o-shopping-bag', 'sort_order' => 27],
            ['name_en' => 'Receptionist', 'name_ar' => 'موظف استقبال', 'name_bn' => 'রিসেপশনিস্ট', 'icon' => 'heroicon-o-phone', 'sort_order' => 28],
            ['name_en' => 'Cashier', 'name_ar' => 'كاشير', 'name_bn' => 'ক্যাশিয়ার', 'icon' => 'heroicon-o-banknotes', 'sort_order' => 29],
            ['name_en' => 'Cook Helper', 'name_ar' => 'مساعد طباخ', 'name_bn' => 'রান্নার সহকারী', 'icon' => 'heroicon-o-fire', 'sort_order' => 30],
            ['name_en' => 'Pastry Chef', 'name_ar' => 'طاهي حلويات', 'name_bn' => 'পেস্ট্রি শেফ', 'icon' => 'heroicon-o-cake', 'sort_order' => 31],
            ['name_en' => 'Baker', 'name_ar' => 'خباز', 'name_bn' => 'বেকার', 'icon' => 'heroicon-o-cake', 'sort_order' => 32],
            ['name_en' => 'Butcher', 'name_ar' => 'جزار', 'name_bn' => 'কসাই', 'icon' => 'heroicon-o-scissors', 'sort_order' => 33],
            ['name_en' => 'Laundry Worker', 'name_ar' => 'عامل مغسلة', 'name_bn' => 'লন্ড্রি কর্মী', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 34],
            ['name_en' => 'Housemaid', 'name_ar' => 'عاملة منزلية', 'name_bn' => 'গৃহকর্মী', 'icon' => 'heroicon-o-home', 'sort_order' => 35],
            ['name_en' => 'Nanny', 'name_ar' => 'جليسة أطفال', 'name_bn' => 'আয়া / শিশু পরিচারিকা', 'icon' => 'heroicon-o-heart', 'sort_order' => 36],
            ['name_en' => 'Elder Caretaker', 'name_ar' => 'مقدم رعاية المسنين', 'name_bn' => 'বৃদ্ধ পরিচারক', 'icon' => 'heroicon-o-heart', 'sort_order' => 37],
            ['name_en' => 'Hospital Helper', 'name_ar' => 'مساعد مستشفى', 'name_bn' => 'হাসপাতাল সহকারী', 'icon' => 'heroicon-o-plus-circle', 'sort_order' => 38],
            ['name_en' => 'Office Boy', 'name_ar' => 'فراش مكتب', 'name_bn' => 'অফিস বয়', 'icon' => 'heroicon-o-building-office', 'sort_order' => 39],
            ['name_en' => 'Warehouse Worker', 'name_ar' => 'عامل مستودع', 'name_bn' => 'গুদামঘর কর্মী', 'icon' => 'heroicon-o-archive-box', 'sort_order' => 40],

            // --- নতুন অতিরিক্ত ক্যাটাগরিগুলো নিচে যুক্ত করা হলো ---
            ['name_en' => 'Accountant (Junior)', 'name_ar' => 'محاسب مبتدئ', 'name_bn' => 'হিসাবরক্ষক (জুনিয়র)', 'icon' => 'heroicon-o-calculator', 'sort_order' => 41],
            ['name_en' => 'Aluminium Fabricator', 'name_ar' => 'فني ألمنيوم', 'name_bn' => 'অ্যালুমিনিয়াম ফেব্রিকেটর', 'icon' => 'heroicon-o-wrench', 'sort_order' => 42],
            ['name_en' => 'Ambulance Driver', 'name_ar' => 'سائق إسعاف', 'name_bn' => 'অ্যাম্বুলেন্স ড্রাইভার', 'icon' => 'heroicon-o-truck', 'sort_order' => 43],
            ['name_en' => 'Auto Electrician', 'name_ar' => 'كهربائي سيارات', 'name_bn' => 'অটো ইলেকট্রিশিয়ান', 'icon' => 'heroicon-o-bolt', 'sort_order' => 44],
            ['name_en' => 'Auto Mechanic', 'name_ar' => 'ميكانيكي سيارات', 'name_bn' => 'অটো মেকানিক', 'icon' => 'heroicon-o-cog-6-tooth', 'sort_order' => 45],
            ['name_en' => 'Auto Painter', 'name_ar' => 'دهان سيارات', 'name_bn' => 'অটো পেন্টার', 'icon' => 'heroicon-o-paint-brush', 'sort_order' => 46],
            ['name_en' => 'Babysitter', 'name_ar' => 'مربيات أطفال', 'name_bn' => 'বেবিসিটার', 'icon' => 'heroicon-o-heart', 'sort_order' => 47],
            ['name_en' => 'Bar Staff', 'name_ar' => 'موظف بار', 'name_bn' => 'বার স্টাফ', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 48],
            ['name_en' => 'Barista', 'name_ar' => 'باريستا', 'name_bn' => 'বারিস্তা', 'icon' => 'heroicon-o-cup-soda', 'sort_order' => 49],
            ['name_en' => 'Bellboy', 'name_ar' => 'حامل حقائب', 'name_bn' => 'বেলবয়', 'icon' => 'heroicon-o-briefcase', 'sort_order' => 50],
            ['name_en' => 'Bus Driver', 'name_ar' => 'سائق حافلة', 'name_bn' => 'বাস ড্রাইভার', 'icon' => 'heroicon-o-truck', 'sort_order' => 51],
            ['name_en' => 'Butler', 'name_ar' => 'رئيس الخدم', 'name_bn' => 'বাটলার', 'icon' => 'heroicon-o-user-check', 'sort_order' => 52],
            ['name_en' => 'Call Center Agent', 'name_ar' => 'موظف مركز اتصالات', 'name_bn' => 'কল সেন্টার এজেন্ট', 'icon' => 'heroicon-o-phone', 'sort_order' => 53],
            ['name_en' => 'Car Washer', 'name_ar' => 'غاسل سيارات', 'name_bn' => 'কার ওয়াশার', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 54],
            ['name_en' => 'Caregiver (Elderly/Patient)', 'name_ar' => 'مقدم رعاية (كبار السن/المرضى)', 'name_bn' => 'কেয়ারগিভার (বয়স্ক/রোগী)', 'icon' => 'heroicon-o-heart', 'sort_order' => 55],
            ['name_en' => 'CCTV Technician', 'name_ar' => 'فني كاميرات مراقبة', 'name_bn' => 'সিসিটিভি টেকনিশিয়ান', 'icon' => 'heroicon-o-video-camera', 'sort_order' => 56],
            ['name_en' => 'Chef', 'name_ar' => 'طاهي', 'name_bn' => 'শেফ', 'icon' => 'heroicon-o-fire', 'sort_order' => 57],
            ['name_en' => 'Cook (Commercial)', 'name_ar' => 'طباخ تجاري', 'name_bn' => 'কুক (বাণিজ্যিক)', 'icon' => 'heroicon-o-fire', 'sort_order' => 58],
            ['name_en' => 'Data Entry Operator', 'name_ar' => 'مدخل بيانات', 'name_bn' => 'ডাটা এন্ট্রি অপারেটর', 'icon' => 'heroicon-o-computer-desktop', 'sort_order' => 59],
            ['name_en' => 'Delivery Driver (Bike/Car)', 'name_ar' => 'سائق توصيل (دراجة/سيارة)', 'name_bn' => 'ডেলিভারি ড্রাইভার (বাইক/কার)', 'icon' => 'heroicon-o-truck', 'sort_order' => 60],
            ['name_en' => 'Dentist Assistant', 'name_ar' => 'مساعد طبيب أسنان', 'name_bn' => 'ডেন্টিস্ট অ্যাসিস্ট্যান্ট', 'icon' => 'heroicon-o-plus-circle', 'sort_order' => 61],
            ['name_en' => 'Denter / Panel Beater', 'name_ar' => 'سمكري سيارات', 'name_bn' => 'ডেন্টার / প্যানেল বিটার', 'icon' => 'heroicon-o-wrench', 'sort_order' => 62],
            ['name_en' => 'Dishwasher', 'name_ar' => 'غاسل أطباق', 'name_bn' => 'ডিশওয়াশার', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 63],
            ['name_en' => 'Elevator Technician', 'name_ar' => 'فني المصاعد', 'name_bn' => 'লিফট টেকনিশিয়ান', 'icon' => 'heroicon-o-wrench-screwdriver', 'sort_order' => 64],
            ['name_en' => 'Fast Food Worker', 'name_ar' => 'عامل وجبات سريعة', 'name_bn' => 'ফাস্ট ফুড কর্মী', 'icon' => 'heroicon-o-fire', 'sort_order' => 65],
            ['name_en' => 'Firefighting Technician', 'name_ar' => 'فني مكافحة الحريق', 'name_bn' => 'ফায়ারফাইটিং টেকনিশিয়ান', 'icon' => 'heroicon-o-shield-check', 'sort_order' => 66],
            ['name_en' => 'Generator Technician', 'name_ar' => 'فني مولدات', 'name_bn' => 'জেনারেটর টেকনিশিয়ান', 'icon' => 'heroicon-o-bolt', 'sort_order' => 67],
            ['name_en' => 'Gypsum Board Installer', 'name_ar' => 'فني جبس بورد', 'name_bn' => 'জিফসাম বোর্ড মিস্ত্রি', 'icon' => 'heroicon-o-squares-2x2', 'sort_order' => 68],
            ['name_en' => 'Heavy Equipment Operator', 'name_ar' => 'مشغل معدات ثقيلة', 'name_bn' => 'হেভি ইকুইপমেন্ট অপারেটর', 'icon' => 'heroicon-o-arrow-up', 'sort_order' => 69],
            ['name_en' => 'Helper (Construction)', 'name_ar' => 'مساعد بناء', 'name_bn' => 'কনস্ট্রাকশন হেলপার', 'icon' => 'heroicon-o-hand-raised', 'sort_order' => 70],
            ['name_en' => 'Hospital Attendant', 'name_ar' => 'مساعد مستشفى', 'name_bn' => 'হাসপাতাল অ্যাটেনডেন্ট', 'icon' => 'heroicon-o-plus-circle', 'sort_order' => 71],
            ['name_en' => 'Hospital Cleaner', 'name_ar' => 'عامل نظافة مستشفى', 'name_bn' => 'হাসপাতাল ক্লিনার', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 72],
            ['name_en' => 'House Driver', 'name_ar' => 'سائق خاص', 'name_bn' => 'হাউস ড্রাইভার', 'icon' => 'heroicon-o-truck', 'sort_order' => 73],
            ['name_en' => 'Housekeeper', 'name_ar' => 'مدبرة منزل', 'name_bn' => 'হাউস কিপার', 'icon' => 'heroicon-o-home', 'sort_order' => 74],
            ['name_en' => 'HVAC Technician', 'name_ar' => 'فني تكييف وتبريد', 'name_bn' => 'এইচভিএসি টেকনিশিয়ান', 'icon' => 'heroicon-o-wrench-screwdriver', 'sort_order' => 75],
            ['name_en' => 'Inventory Controller', 'name_ar' => 'مراقب مخزون', 'name_bn' => 'ইনভেন্টরি কন্ট্রোলার', 'icon' => 'heroicon-o-archive-box', 'sort_order' => 76],
            ['name_en' => 'Janitor', 'name_ar' => 'عامل صيانة ونظافة', 'name_bn' => 'জেনিটর', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 77],
            ['name_en' => 'Laboratory Technician', 'name_ar' => 'فني مختبر', 'name_bn' => 'ল্যাবরেটরি টেকনিশিয়ান', 'icon' => 'heroicon-o-beaker', 'sort_order' => 78],
            ['name_en' => 'Landscaper', 'name_ar' => 'منسق حدائق', 'name_bn' => 'ল্যান্ডস্কেপার', 'icon' => 'heroicon-o-sun', 'sort_order' => 79],
            ['name_en' => 'Livestock Handler', 'name_ar' => 'عامل مواشي', 'name_bn' => 'লাইভস্টক হ্যান্ডলার', 'icon' => 'heroicon-o-sun', 'sort_order' => 80],
            ['name_en' => 'Logistics Assistant', 'name_ar' => 'مساعد لوجستي', 'name_bn' => 'লজিস্টিকস অ্যাসিস্ট্যান্ট', 'icon' => 'heroicon-o-archive-box', 'sort_order' => 81],
            ['name_en' => 'Merchandiser', 'name_ar' => 'منسق بضائع', 'name_bn' => 'মার্চেন্ডাইজার', 'icon' => 'heroicon-o-shopping-bag', 'sort_order' => 82],
            ['name_en' => 'Nursing Aid', 'name_ar' => 'مساعد تمريض', 'name_bn' => 'নার্সিং এইড', 'icon' => 'heroicon-o-plus-circle', 'sort_order' => 83],
            ['name_en' => 'Office Admin', 'name_ar' => 'إداري مكتب', 'name_bn' => 'অফিস এডমিন', 'icon' => 'heroicon-o-building-office', 'sort_order' => 84],
            ['name_en' => 'Office Cleaner', 'name_ar' => 'عامل نظافة مكاتب', 'name_bn' => 'অফিস ক্লিনার', 'icon' => 'heroicon-o-sparkles', 'sort_order' => 85],
            ['name_en' => 'Packaging Worker', 'name_ar' => 'عامل تغليف', 'name_bn' => 'প্যাকেজিং কর্মী', 'icon' => 'heroicon-o-archive-box-arrow-down', 'sort_order' => 86],
            ['name_en' => 'Pest Control Worker', 'name_ar' => 'عامل مكافحة الحشرات', 'name_bn' => 'পেস্ট কন্ট্রোল কর্মী', 'icon' => 'heroicon-o-shield-check', 'sort_order' => 87],
            ['name_en' => 'Pharmacy Assistant', 'name_ar' => 'مساعد صيدلي', 'name_bn' => 'ফার্মেসি অ্যাসিস্ট্যান্ট', 'icon' => 'heroicon-o-plus-circle', 'sort_order' => 88],
            ['name_en' => 'Pipe Fitter', 'name_ar' => 'فني أنابيب', 'name_bn' => 'পাইপ ফিটার', 'icon' => 'heroicon-o-wrench-screwdriver', 'sort_order' => 89],
            ['name_en' => 'Private Cook', 'name_ar' => 'طباخ خاص', 'name_bn' => 'প্রাইভেট কুক', 'icon' => 'heroicon-o-fire', 'sort_order' => 90],
            ['name_en' => 'Production Worker', 'name_ar' => 'عامل إنتاج', 'name_bn' => 'প্রোডাকশন কর্মী', 'icon' => 'heroicon-o-cog', 'sort_order' => 91],
            ['name_en' => 'Radiographer', 'name_ar' => 'فني أشعة', 'name_bn' => 'রেডিওগ্রাফার', 'icon' => 'heroicon-o-beaker', 'sort_order' => 92],
            ['name_en' => 'Refrigeration Technician', 'name_ar' => 'فني تبريد', 'name_bn' => 'রেফ্রিজারেশন টেকনিশিয়ান', 'icon' => 'heroicon-o-wrench-screwdriver', 'sort_order' => 93],
            ['name_en' => 'Rigger', 'name_ar' => 'فني تربيط', 'name_bn' => 'রিগার', 'icon' => 'heroicon-o-wrench', 'sort_order' => 94],
            ['name_en' => 'Room Attendant', 'name_ar' => 'عامل غرف', 'name_bn' => 'রুম অ্যাটেনডেন্ট', 'icon' => 'heroicon-o-home', 'sort_order' => 95],
            ['name_en' => 'Shop Assistant', 'name_ar' => 'مساعد محل', 'name_bn' => 'শপ অ্যাসিস্ট্যান্ট', 'icon' => 'heroicon-o-shopping-bag', 'sort_order' => 96],
            ['name_en' => 'Shuttering Carpenter', 'name_ar' => 'نجار مسلح', 'name_bn' => 'শাটারিং কার্পেন্টার', 'icon' => 'heroicon-o-wrench', 'sort_order' => 97],
            ['name_en' => 'Storekeeper/Warehouse Staff', 'name_ar' => 'أمين مخزن / أمين مستودع', 'name_bn' => 'স্টোরকিপার / ওয়ারহাউস স্টাফ', 'icon' => 'heroicon-o-archive-box', 'sort_order' => 98],
            ['name_en' => 'Structural Fabricator', 'name_ar' => 'فني تركيب هياكل معدنية', 'name_bn' => 'স্ট্রাকচারাল ফেব্রিকেটর', 'icon' => 'heroicon-o-wrench', 'sort_order' => 99],
            ['name_en' => 'Surveyor', 'name_ar' => 'مساح', 'name_bn' => 'সার্ভেয়ার', 'icon' => 'heroicon-o-map-pin', 'sort_order' => 100],
            ['name_en' => 'Taxi Driver', 'name_ar' => 'سائق سيارة أجرة', 'name_bn' => 'ট্যাক্সি ড্রাইভার', 'icon' => 'heroicon-o-truck', 'sort_order' => 101],
            ['name_en' => 'Tea Boy / Office Boy', 'name_ar' => 'عامل بوفيه ومكتب', 'name_bn' => 'টি বয় / অফিস বয়', 'icon' => 'heroicon-o-cup-soda', 'sort_order' => 102],
            ['name_en' => 'Tile Fixer', 'name_ar' => 'مبلط', 'name_bn' => 'টাইলস মিস্ত্রি', 'icon' => 'heroicon-o-squares-2x2', 'sort_order' => 103],
            ['name_en' => 'Tire Technician (Vulcanizer)', 'name_ar' => 'فني إطارات', 'name_bn' => 'টায়ার টেকনিশিয়ান', 'icon' => 'heroicon-o-cog-6-tooth', 'sort_order' => 104],
            ['name_en' => 'Trailer Driver', 'name_ar' => 'سائق مقطورة', 'name_bn' => 'ট্রেইলার ড্রাইভার', 'icon' => 'heroicon-o-truck', 'sort_order' => 105],
            ['name_en' => 'Waiter/Waitress', 'name_ar' => 'نادل / نادلة', 'name_bn' => 'ওয়েটার / ওয়েট্রেস', 'icon' => 'heroicon-o-user', 'sort_order' => 106],
            ['name_en' => 'Watchman', 'name_ar' => 'حارس', 'name_bn' => 'ওয়াচম্যান', 'icon' => 'heroicon-o-shield-check', 'sort_order' => 107],
            ['name_en' => 'Others', 'name_ar' => 'أخرى', 'name_bn' => 'অন্যান্য', 'icon' => 'heroicon-o-ellipsis-horizontal', 'sort_order' => 999],
        ];

        foreach ($categories as $cat) {
            DB::table('skill_categories')->updateOrInsert(
                ['name_en' => $cat['name_en']],
                array_merge($cat, ['is_active' => true])
            );
        }

        $this->command->info('✅ SkillCategories সিড হয়েছে: ' . count($categories) . 'টি ক্যাটাগরি');
    }
}